CREATE DATABASE data_analytics;
USE data_analytics;
SHOW TABLES;
SELECT *
FROM customers
LIMIT 20;

-- 1 -> WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS FEMALE CUSTOMERS?
 SELECT gender, SUM(purchase_amount) as revenue 
 FROM customers
 GROUP BY gender;
 
-- 2-> Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id,
       purchase_amount
FROM customers
WHERE discount_applied = 'Yes'
  AND purchase_amount >
      (
        SELECT AVG(purchase_amount)
        FROM customers
      );
      
-- 3-> Which are the top 5 products with the highest average review rating??
 SELECT item_purchased,
	ROUND(AVG(review_rating), 2) AS avg_rating
FROM customers 
GROUP BY item_purchased 
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- 4-> compare the average Purchase Amount between Standard and Express Shipping?? 
SELECT shipping_type, 
ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customers
WHERE shipping_type IN('Standard', 'Express')
GROUP BY shipping_type;

-- 5-> Do describe customers spend more? compare average spend and total revenue between 
-- suscribers and non-suscribers.
SELECT subscription_status,
	COUNT(customer_id) AS total_customers,
	ROUND(AVG(purchase_amount),2) AS average_spend,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue, average_spend;

-- 6-> Which 5 products have the highest percentage of perchase with discount applied?
SELECT item_purchased,
	ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) /count(*) ,2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC 
LIMIT 5;

-- 7-> Segment customers into NEW, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment

SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customers
GROUP BY customer_segment
ORDER BY customer_count DESC;

-- 8-> WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY
WITH item_counts AS (
SELECT 
	category,
    item_purchased,
    COUNT(customer_id) AS total_orders
    FROM customers
    GROUP BY category, item_purchased
),
ranked_products AS (
	SELECT
    category, 
    item_purchased,
    total_orders,
    ROW_NUMBER() OVER (
    PARTITION BY category
    ORDER BY total_orders DESC
	) AS rn
FROM item_counts
)
SELECT
	category,
    item_purchased,
    total_orders
    FROM ranked_products
    WHERE rn <=3;
    
-- 9 -> Are customers who are  repeat buyers(more than 5 previous purchase) also likely to suscribe?
SELECT subscription_status,
count(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases	> 5
GROUP BY subscription_status;


-- 10 -> What is the revenue contribution of eacch age group??
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;
